Unit Tests for Apache Ignite
mindsdb/mindsdb-status pull request #7
Opened 2023-08-01 19:49 UTC by MinuraPunchihewa

This PR includes the unit tests for the Apache Ignite integration and also includes a docker-compose.yml file, which allows a Docker container running Apache Ignite to be spun up. This file defines the skeleton for adding other services for the integrations that are to be tested.

2023-08-02 12:00 UTC, ZoranPandovski requested changes

2023-08-02 12:00 UTC, ZoranPandovski commented on utils/config_example.json
>      }
Can you also include the apache_ignite example here ?

2023-08-02 19:50 UTC, MinuraPunchihewa commented on utils/config_example.json
>      }
I've added it, Zoran.

2023-08-03 12:07 UTC, ZoranPandovski approved these changes

2023-08-03 12:10 UTC, merged